### ISSUE TITLE
Errors on execution

### ISSUE THREAD

**Issue by meena-devi** [chawat/PolarCodes#5]

**Comment by chawat** [comment]
Please follow the updated README to execute without any compilation errors. I am closing this issue for now :)

**Comment by meena-devi** [comment]
Hi Chawat,
Thank you for the quick response.
I have executed as per the README file, but it is showing some corrupted receptions when SNR value is passed to rxData. Some help on this please about how to rectify this.
Regards,
meena-devi

**Comment by chawat** [comment]
So, the successive cancellation receiver for polar decoding is yet to be tested. There are some corner cases where the decoder will/is failing. Thus, this is expected. Hopefully, if you increase the SNR value, you shouldn't have any corrupted reception. I hope that answers your query.

Best Regards,
Chawat

**Comment by chawat** [comment]
I have made some minor changes to the mainSystem.c after previous updates to the AWGN channel module. Please update your copy of the repo and run the system once again. Try playing with SNR_dB and see how the Bit Error Rate varies, for your better understanding.

**Comment by meena-devi** [comment]
Thank you Chawat for your quick response and clarifying the doubts. Let me update to the latest commit and check.
